### PR TITLE
Full Stack Challenge - Álvaro palma

### PR DESCRIPTION
**Pull request by Arvo-palma**
Hello, this is my test. Any questions or doubts, please feel free to ask!

image

### CODE REVIEW

**Comment by amaralc** [comment]
Hello @Arvo-palma, I see in the documentation that you would send the .env file but I still do not have it. Can you send it to calil.amaral@dynamox.net?

**Comment by calil-amaral-dynamox** [comment]
Hello @Arvo-palma, I see in the documentation that you would send the .env file but I still do not have it. Can you send it to [calil.amaral@dynamox.net](mailto:calil.amaral@dynamox.net)?

**Comment by calil-amaral-dynamox** [comment]
IN PROGRESS

1 - Authentication

1. [ ] As a user, I want to log in using a fixed email and password so that I can access private routes.
1. [ ] As a user, I want to be able to log out of the system so that I can prevent unauthorized access to my account.
1. [ ] No private routes should be accessible without authentication.

2 - Machine Management

1. [ ] As a user, I want to create a new machine with an arbitrary name and with a type selected from a list ["Pump", "Fan"] so that I can manage it later.
1. [ ] As a user, I want to change the attributes (name and type) of a machine after creating it so that I can keep the machine information updated.
1. [ ] As a user, I want to delete a machine when it is no longer in use so that it doesn't clutter the system.

3 - Monitoring Points and Sensors Management

1. [ ] As a user, I want to create at least two monitoring points with arbitrary names for an existing machine, so that I can monitor the machine's performance.
1. [ ] As a user, I want to associate a sensor to an existing monitoring point so that I can monitor the machine's performance. The sensor should have a unique ID, and the sensor model name should be one of ["TcAg", "TcAs", "HF+"].
1. [ ] As a user, I want the system to prevent me from setting up "TcAg" and "TcAs" sensors for machines of the type "Pump".
1. [ ] As a user, I want to see all my monitoring points in a paginated list so that I can manage them. The list should display up to 5 monitoring points per page and should include the following information: "Machine Name", "Machine Type", "Monitoring Point Name", and "Sensor Model".
1. [ ] As a user, I want to sort the monitoring points list by any of its columns in ascending or descending order, so that I can easily find the information I'm looking for.

4 - Ambiguity Handling

1. [ ] Make reasonable assumptions and design the application accordingly for any ambiguities in the challenge.
1. [ ] Document your assumptions in the README file.

5 - Technical requirements

1. [ ] Use TypeScript.
1. [ ] Use React.
1. [ ] Use Redux for managing global states.
1. [ ] Use Redux Thunks or Redux Saga for managing asynchronous side effects.
1. [ ] Use Next.js or Vite.
1. [ ] Use Material UI 5 for styling the application.
1. [ ] Create reusable components.
1. [ ] The code is well-organized and documented.
1. [ ] The application layout is responsive.
The choice of remaining tools is at your discretion.

6 - Bonus

1. [ ] Implement unit tests for the application (let us know how to run them, otherwise we won't be able to evaluate).
1. [ ] Implement your own back-end code. If you pick this option, write it using NodeJS JavaScript runtime (not Java, not PHP...). Although we also work with Python here, we are looking for JavaScript related skills in this test.
1. [ ] If you choose to implement your own back-end, we encourage you to use either PostgreSQL or MongoDB as a persistence layer.
1. [ ] If you choose to use PostgreSQL, use Prisma ORM (or even try Drizzle, or Kysely) to interact with PostgreSQL.
1. [ ] If you choose to use MongoDB, use Mongoose ORM to interact with the database;
1. [ ] Use Nest.js Framework for the back-end (we are moving some services to that tool).
1. [ ] Use Nx to manage the whole application as a monorepo (we use that tool a lot here).
1. [ ] Add e2e tests with Cypress (use it to test a full user flow).
1. [ ] If you were provided with a baseline code, identify any areas of bad code or suboptimal implementations and refactor them.
1. [ ] Deploy your application to a cloud provider and provide a link for the running app.

In general we will be looking for the following:

1. [ ] Anyone should be able to follow the instructions and run the application.
1. [ ] User stories were implemented according to the functional requirements.
1. [ ] Front-end code is successfully integrated with a back-end API (either a fake one, or one you built yourself).
~1. [ ] Ability to refactor existing code (if applicable) and write unit tests for the written code.~
1. [ ] Adherence to best practices in front-end development.
1. [ ] Problem-solving skills and ability to handle ambiguity.
1. [ ] Code quality, readability, and maintainability.

**Comment by calil-amaral-dynamox** [comment]
@Arvo-palma, it was not possible to connect with the MongoDb instance with the connection string you provided. Can you check that all IP addresses are whitelisted?

image

**Comment by Arvo-palma** [comment]
Sorry Calil, I forgot to respond here. I have already released universal access to the database, I apologize for the interruption. If you have any problems, I'm at your disposal.

**Comment by italorockenbachamaral** [comment]
EVALUATION IN PROGRESS...

1 - Authentication

1. [x] As a user, I want to log in using a fixed email and password so that I can access private routes.
1. [x] As a user, I want to be able to log out of the system so that I can prevent unauthorized access to my account.
1. [x] No private routes should be accessible without authentication.

>  There is no UI for error handling  when trying to login with wrong credentials 👎
>  There is a single browser url to manage every entity. 👎
> API Code: Interesting way to do user authentication together with guards and cookies 👍

2 - Machine Management

1. [x] As a user, I want to create a new machine with an arbitrary name and with a type selected from a list ["Pump", "Fan"] so that I can manage it later.
>  I was able to create machine 👍
>  After creating, type and status input's are cleared but  name input is not cleared 👎

1. [x] As a user, I want to change the attributes (name and type) of a machine after creating it so that I can keep the machine information updated.
>  I was able to update a machine 👍
>  After updating, nor id or name input is cleared 👎

1. [x] As a user, I want to delete a machine when it is no longer in use so that it doesn't clutter the system.
> It was a good assumption to let the user delete only inactive machines 👍
> The API response made the limitation obvious with a clear response message 👍
> There is no UI for error handling for what went wrong when trying to delete a active machine 👎
>  After deleting, id input is not cleared 👎
>  API Code: The code is clean, easy to understand and descriptive variables 👍

> Overall: user workflow is not very intuitive 👎

3 - Monitoring Points and Sensors Management

1. [x] As a user, I want to create at least two monitoring points with arbitrary names for an existing machine, so that I can monitor the machine's performance.
> Label name is set as "create machine" , this can cause user confusion👎
> I was able to create a monitoring point 👍
> After creating, machine name and sensor is cleared but spot name input is not cleared 👎

1. [x] As a user, I want to associate a sensor to an existing monitoring point so that I can monitor the machine's performance. The sensor should have a unique ID, and the sensor model name should be one of ["TcAg", "TcAs", "HF+"].
1. [x] As a user, I want the system to prevent me from setting up "TcAg" and "TcAs" sensors for machines of the type "Pump".
> I wasn't able to set TcAg or TcAs sensors to pump machine 👍

1. [x] As a user, I want to see all my monitoring points in a paginated list so that I can manage them. The list should display up to 5 monitoring points per page and should include the following information: "Machine Name", "Machine Type", "Monitoring Point Name", and "Sensor Model".
> On screens where the table does not fit (1450x960) the overflow is configured for the page and not for the table 👎
> In the "name" column, the name of the machine is being rendered and not the name of the monitoring point 👎

1. [x] As a user, I want to sort the monitoring points list by any of its columns in ascending or descending order, so that I can easily find the information I'm looking for.
> Sometimes the sorting behavior was only sorting on the second click on the column 👎
> After I clicked on delete the monitoring points selected in the table, they remain in the table and selected and I can keep clicking on the delete icon numerous times and no error is thrown. 👎
> So that the deleted monitoring points do not appear in the table, I needed to reload the page 👎

> Overall: Every time I refresh the page I am returned to the login screen, after a few microseconds I am automatically logged in and go to the "successfully logged in" screen and not where I was previously. 👎

4 - Ambiguity Handling

1. [x] Make reasonable assumptions and design the application accordingly for any ambiguities in the challenge.
1. [ ] Document your assumptions in the README file.

5 - Technical requirements

1. [x] Use TypeScript.
1. [x] Use React.
1. [ ] Use Redux for managing global states.
1. [ ] Use Redux Thunks or Redux Saga for managing asynchronous side effects.
1. [ ] Use Next.js or Vite.
1. [ ] Use Material UI 5 for styling the application.
1. [ ] Create reusable components.
1. [ ] The code is well-organized and documented.
1. [ ] The application layout is responsive.
The choice of remaining tools is at your discretion.

6 - Bonus

1. [ ] Implement unit tests for the application (let us know how to run them, otherwise we won't be able to evaluate).
1. [ ] Implement your own back-end code. If you pick this option, write it using NodeJS JavaScript runtime (not Java, not PHP...). Although we also work with Python here, we are looking for JavaScript related skills in this test.
1. [ ] If you choose to implement your own back-end, we encourage you to use either PostgreSQL or MongoDB as a persistence layer.
1. [ ] If you choose to use PostgreSQL, use Prisma ORM (or even try Drizzle, or Kysely) to interact with PostgreSQL.
1. [ ] If you choose to use MongoDB, use Mongoose ORM to interact with the database;
1. [ ] Use Nest.js Framework for the back-end (we are moving some services to that tool).
1. [ ] Use Nx to manage the whole application as a monorepo (we use that tool a lot here).
1. [ ] Add e2e tests with Cypress (use it to test a full user flow).
1. [ ] If you were provided with a baseline code, identify any areas of bad code or suboptimal implementations and refactor them.
1. [ ] Deploy your application to a cloud provider and provide a link for the running app.

**Comment by calil-amaral-dynamox** [comment]
@Arvo-palma Thanks for your PR submission! Your implementation was evaluated and will be closed now. Wait for a contact by e-mail from our team.

**Pull request closed without merging**
